---
site_name: osbm
repo_url: https://github.com/osbm/osbm-pypi/
repo_name: osbm
edit_uri: ./edit/main/docs/

site_name: osbm
site_description: Documentation for the osbm python package
site_author: Osman
site_url: https://osbm.readthedocs.io/en/latest/

theme:
  name: mkdocs
