name: Publish to PYPI and github

on:
  push:
    paths:
      - osbm/VERSION
      - .github/workflows/publish.yml

jobs:
  publish_package:
    name: Publish the osbm package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build the package
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
      
      - name: Assign release version from osbm/VERSION to Env variable
        run: |
          echo "version_file=$(cat osbm/VERSION)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.version_file }}
          release_name: Release ${{ env.version_file }}
          draft: false
          prerelease: false

      - name: release
        uses: softprops/action-gh-release@v1
          